Proper error handling
dnsimple/dnsimple-rust pull request #22
Opened 2022-05-23 13:46 UTC by ecomba

This PR changes the way we did error handling.

2022-06-04 00:13 UTC, onlyhavecans requested changes
The error messages returned are inconsistent.

The hardcoded ones are fine but the ones that use variables are wrapping the error Enum names in extra quotes which will make this hard to use in code.
```NotFound("\"Domain `example.com` not found\"")```

When displayed they also have the extra `Message: ` as well as the quotes
```Message: "Domain `example.com` not found"```

With Transport Errors, it also doubles the error message. Giving the error message, then giving it again in parentheses

`Transport Error – https://api.sandbox.dnsimple.com/v2/whoami: Dns Failed: resolve dns name 'api.sandbox.dnsimple.com:443': failed to lookup address information: nodename nor servname provided, or not known(https://api.sandbox.dnsimple.com/v2/whoami: Dns Failed: resolve dns name 'api.sandbox.dnsimple.com:443': failed to lookup address information: nodename nor servname provided, or not known)`



I haven't tested all the possible errors yet but I have started expanding the API examples to help with intigrations tests.

2022-06-06 12:30 UTC, ecomba commented
> The error messages returned are inconsistent.
> 
> The hardcoded ones are fine but the ones that use variables are wrapping the error Enum names in extra quotes which will make this hard to use in code. `` NotFound("\"Domain `example.com` not found\"") ``
> 
> When displayed they also have the extra `Message: ` as well as the quotes `` Message: "Domain `example.com` not found" ``
> 
> Transport Errors also double the error message. Giving the error message, then giving it again in parentheses
> 
> `Transport Error – https://api.sandbox.dnsimple.com/v2/whoami: Dns Failed: resolve dns name 'api.sandbox.dnsimple.com:443': failed to lookup address information: nodename nor servname provided, or not known(https://api.sandbox.dnsimple.com/v2/whoami: Dns Failed: resolve dns name 'api.sandbox.dnsimple.com:443': failed to lookup address information: nodename nor servname provided, or not known)`
> 
> I haven't tested all the possible errors yet but [I have started expanding the API examples to help](https://github.com/dnsimple/dnsimple-api-examples/pull/18) with integration tests.

I have cleaned the error messages. As it turns out when rust puts a string inside a string (from JSON) it adds quotation marks, which it then escapes. I remember googling this before and not finding any satisfactory solution (which was the reason for me leaving it as is in the first place). I've now made sure to parse the string coming from JSON and remove the `"` from it.

As for the `Transport` Error, there was a genuine bug in there where we only took one of the variables and used it to fill in both arguments; this has been fixed now as well.

2022-06-06 12:31 UTC, ecomba commented on src/dnsimple.rs
>      }
It is(n't). When I was cleaning the code for the Error messages I found some code duplication that was bugging me and I removed it

2022-06-10 16:22 UTC, onlyhavecans requested changes
I have some small suggestions to make the dev experience better and more consistent. Also pushed minor changes for cleanup.

2022-06-10 16:22 UTC, onlyhavecans commented on tests/zones_test.rs
> +        "Message: Could not query zone, connection timed out",
I think we shouldn't change the message and add `Message: `

2022-06-14 21:29 UTC, onlyhavecans approved these changes
I made a few minor changes and I think this is good to go!
GG on this refactor! 👏🏻

2022-06-15 07:43 UTC, merged